/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_vue;

import package_controleur.DateTimeManager;

/**
 *
 * @author hugon
 */
public class EDT_Window extends javax.swing.JFrame {

    // Variables pour savoir quelle fenetre est ouverte
    private boolean edtSelected = true;
    private boolean recapSelected = false;
    private boolean majSelected = false;
    private boolean reportingSelected = false;
    // Fin
    
    // Variable pour l'heure et la date
    //private DateTimeManager dtm = new DateTimeManager();
    // Fin
    
    
    
    /**
     * Creates new form EDT_Window
     */
    public EDT_Window() {
        initComponents();
        DateTimeManager.Clock(dateLabel, heureLabel); //Modifie l'heure et la date toutes les 1s
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstBackgroundPanel = new javax.swing.JPanel();
        leftGreenPanel = new javax.swing.JPanel();
        iconEce = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        welcomeLabel = new javax.swing.JLabel();
        nameUserLabel = new javax.swing.JLabel();
        droitLabel = new javax.swing.JLabel();
        promotionLabel = new javax.swing.JLabel();
        tdLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        emploidutempsLabel = new javax.swing.JLabel();
        recapitulatifLabel = new javax.swing.JLabel();
        reportingLabel = new javax.swing.JLabel();
        gestionnaireLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        dateLabel = new javax.swing.JLabel();
        heureLabel = new javax.swing.JLabel();
        deconnexionLabel = new javax.swing.JLabel();
        edtPanel = new javax.swing.JPanel();
        semainePickerPanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jToggleButton49 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton51 = new javax.swing.JToggleButton();
        jToggleButton52 = new javax.swing.JToggleButton();
        edtAffichagePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emploi du temps");
        setResizable(false);

        firstBackgroundPanel.setBackground(new java.awt.Color(204, 204, 204));

        leftGreenPanel.setBackground(new java.awt.Color(0, 113, 121));

        iconEce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ece_200.png"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(204, 204, 204));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Bienvenue,");

        nameUserLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        nameUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameUserLabel.setText("Hugo Navillod");

        droitLabel.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        droitLabel.setForeground(new java.awt.Color(204, 204, 204));
        droitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        droitLabel.setText("Etudiant");

        promotionLabel.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        promotionLabel.setForeground(new java.awt.Color(204, 204, 204));
        promotionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        promotionLabel.setText("ING3");

        tdLabel.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        tdLabel.setForeground(new java.awt.Color(204, 204, 204));
        tdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tdLabel.setText("TD05");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        emploidutempsLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        emploidutempsLabel.setForeground(new java.awt.Color(255, 255, 255));
        emploidutempsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emploidutempsLabel.setText("Emploi Du Temps");
        emploidutempsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emploidutempsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emploidutempsLabelMouseClicked(evt);
            }
        });

        recapitulatifLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        recapitulatifLabel.setForeground(new java.awt.Color(153, 153, 153));
        recapitulatifLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recapitulatifLabel.setText("Récapitulatif Période");
        recapitulatifLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recapitulatifLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recapitulatifLabelMouseClicked(evt);
            }
        });

        reportingLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        reportingLabel.setForeground(new java.awt.Color(153, 153, 153));
        reportingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportingLabel.setText("Reporting");
        reportingLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportingLabelMouseClicked(evt);
            }
        });

        gestionnaireLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        gestionnaireLabel.setForeground(new java.awt.Color(153, 153, 153));
        gestionnaireLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gestionnaireLabel.setText("Gestionnaire EDT");
        gestionnaireLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gestionnaireLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionnaireLabelMouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));

        dateLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("16 Mai 2020");

        heureLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        heureLabel.setForeground(new java.awt.Color(255, 255, 255));
        heureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heureLabel.setText("17:30:49");

        deconnexionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deconnexionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DeconnexionIcon_50.png"))); // NOI18N
        deconnexionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deconnexionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deconnexionLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftGreenPanelLayout = new javax.swing.GroupLayout(leftGreenPanel);
        leftGreenPanel.setLayout(leftGreenPanelLayout);
        leftGreenPanelLayout.setHorizontalGroup(
            leftGreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deconnexionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(emploidutempsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(recapitulatifLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftGreenPanelLayout.createSequentialGroup()
                .addComponent(iconEce)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(droitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gestionnaireLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftGreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftGreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(promotionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftGreenPanelLayout.setVerticalGroup(
            leftGreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftGreenPanelLayout.createSequentialGroup()
                .addComponent(iconEce, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(droitLabel)
                .addGap(5, 5, 5)
                .addComponent(promotionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tdLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emploidutempsLabel)
                .addGap(18, 18, 18)
                .addComponent(recapitulatifLabel)
                .addGap(18, 18, 18)
                .addComponent(reportingLabel)
                .addGap(18, 18, 18)
                .addComponent(gestionnaireLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deconnexionLabel)
                .addContainerGap())
        );

        semainePickerPanel.setBackground(new java.awt.Color(0, 113, 121));
        semainePickerPanel.setLayout(new java.awt.GridLayout(2, 53, 5, 0));

        jToggleButton1.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton1.setSelected(true);
        jToggleButton1.setText("1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton1);

        jToggleButton2.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton2.setText("2");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton2);

        jToggleButton3.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton3.setText("2");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton3);

        jToggleButton4.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton4.setText("2");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton4);

        jToggleButton5.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton5.setText("2");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton5);

        jToggleButton6.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton6.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton6.setText("2");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton6);

        jToggleButton7.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton7);
        jToggleButton7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton7.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton7.setText("2");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton7);

        jToggleButton8.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton8);
        jToggleButton8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton8.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton8.setText("2");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton8);

        jToggleButton9.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton9.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton9.setText("2");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton9);

        jToggleButton10.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton10.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton10.setText("2");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton10);

        jToggleButton11.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton11);
        jToggleButton11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton11.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton11.setText("2");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton11);

        jToggleButton12.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton12);
        jToggleButton12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton12.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton12.setText("2");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton12);

        jToggleButton13.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton13);
        jToggleButton13.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton13.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton13.setText("2");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton13);

        jToggleButton14.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton14);
        jToggleButton14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton14.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton14.setText("2");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton14);

        jToggleButton15.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton15);
        jToggleButton15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton15.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton15.setText("2");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton15);

        jToggleButton16.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton16);
        jToggleButton16.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton16.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton16.setText("2");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton16);

        jToggleButton17.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton17);
        jToggleButton17.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton17.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton17.setText("2");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton17);

        jToggleButton18.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton18);
        jToggleButton18.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton18.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton18.setText("2");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton18);

        jToggleButton19.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton19);
        jToggleButton19.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton19.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton19.setText("2");
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton19);

        jToggleButton20.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton20);
        jToggleButton20.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton20.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton20.setText("2");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton20);

        jToggleButton21.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton21);
        jToggleButton21.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton21.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton21.setText("2");
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton21);

        jToggleButton22.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton22);
        jToggleButton22.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton22.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton22.setText("2");
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton22);

        jToggleButton23.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton23);
        jToggleButton23.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton23.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton23.setText("2");
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton23);

        jToggleButton24.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton24);
        jToggleButton24.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton24.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton24.setText("2");
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton24);

        jToggleButton25.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton25);
        jToggleButton25.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton25.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton25.setText("2");
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton25);

        jToggleButton26.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton26);
        jToggleButton26.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton26.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton26.setText("2");
        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton26);

        jToggleButton27.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton27);
        jToggleButton27.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton27.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton27.setText("2");
        jToggleButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton27ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton27);

        jToggleButton28.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton28);
        jToggleButton28.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton28.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton28.setText("2");
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton28);

        jToggleButton29.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton29);
        jToggleButton29.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton29.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton29.setText("2");
        jToggleButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton29ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton29);

        jToggleButton30.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton30);
        jToggleButton30.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton30.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton30.setText("2");
        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton30);

        jToggleButton31.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton31);
        jToggleButton31.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton31.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton31.setText("2");
        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton31);

        jToggleButton32.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton32);
        jToggleButton32.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton32.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton32.setText("2");
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton32);

        jToggleButton33.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton33);
        jToggleButton33.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton33.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton33.setText("2");
        jToggleButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton33ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton33);

        jToggleButton34.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton34);
        jToggleButton34.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton34.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton34.setText("2");
        jToggleButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton34ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton34);

        jToggleButton35.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton35);
        jToggleButton35.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton35.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton35.setText("2");
        jToggleButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton35ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton35);

        jToggleButton36.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton36);
        jToggleButton36.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton36.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton36.setText("2");
        jToggleButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton36ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton36);

        jToggleButton37.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton37);
        jToggleButton37.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton37.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton37.setText("2");
        jToggleButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton37ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton37);

        jToggleButton38.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton38);
        jToggleButton38.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton38.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton38.setText("2");
        jToggleButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton38ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton38);

        jToggleButton39.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton39);
        jToggleButton39.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton39.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton39.setText("2");
        jToggleButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton39ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton39);

        jToggleButton40.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton40);
        jToggleButton40.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton40.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton40.setText("2");
        jToggleButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton40ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton40);

        jToggleButton41.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton41);
        jToggleButton41.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton41.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton41.setText("2");
        jToggleButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton41ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton41);

        jToggleButton42.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton42);
        jToggleButton42.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton42.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton42.setText("2");
        jToggleButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton42ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton42);

        jToggleButton43.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton43);
        jToggleButton43.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton43.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton43.setText("2");
        jToggleButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton43ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton43);

        jToggleButton44.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton44);
        jToggleButton44.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton44.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton44.setText("2");
        jToggleButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton44ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton44);

        jToggleButton45.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton45);
        jToggleButton45.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton45.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton45.setText("2");
        jToggleButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton45ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton45);

        jToggleButton46.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton46);
        jToggleButton46.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton46.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton46.setText("2");
        jToggleButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton46ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton46);

        jToggleButton47.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton47);
        jToggleButton47.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton47.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton47.setText("2");
        jToggleButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton47ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton47);

        jToggleButton48.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton48);
        jToggleButton48.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton48.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton48.setText("2");
        jToggleButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton48ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton48);

        jToggleButton49.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton49);
        jToggleButton49.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton49.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton49.setText("2");
        jToggleButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton49ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton49);

        jToggleButton50.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton50);
        jToggleButton50.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton50.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton50.setText("2");
        jToggleButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton50ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton50);

        jToggleButton51.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton51);
        jToggleButton51.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton51.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton51.setText("2");
        jToggleButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton51ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton51);

        jToggleButton52.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jToggleButton52);
        jToggleButton52.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jToggleButton52.setForeground(new java.awt.Color(204, 0, 153));
        jToggleButton52.setText("2");
        jToggleButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton52ActionPerformed(evt);
            }
        });
        semainePickerPanel.add(jToggleButton52);

        edtAffichagePanel.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout edtAffichagePanelLayout = new javax.swing.GroupLayout(edtAffichagePanel);
        edtAffichagePanel.setLayout(edtAffichagePanelLayout);
        edtAffichagePanelLayout.setHorizontalGroup(
            edtAffichagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        edtAffichagePanelLayout.setVerticalGroup(
            edtAffichagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout edtPanelLayout = new javax.swing.GroupLayout(edtPanel);
        edtPanel.setLayout(edtPanelLayout);
        edtPanelLayout.setHorizontalGroup(
            edtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edtPanelLayout.createSequentialGroup()
                .addGroup(edtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(semainePickerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtAffichagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        edtPanelLayout.setVerticalGroup(
            edtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edtPanelLayout.createSequentialGroup()
                .addComponent(semainePickerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtAffichagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout firstBackgroundPanelLayout = new javax.swing.GroupLayout(firstBackgroundPanel);
        firstBackgroundPanel.setLayout(firstBackgroundPanelLayout);
        firstBackgroundPanelLayout.setHorizontalGroup(
            firstBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstBackgroundPanelLayout.createSequentialGroup()
                .addComponent(leftGreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        firstBackgroundPanelLayout.setVerticalGroup(
            firstBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftGreenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(edtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Si on clique sur l'emploi du temps
    private void emploidutempsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emploidutempsLabelMouseClicked
        // TODO add your handling code here:
        if(!edtSelected) //Si il n'est pas selectionne
        {
            //On change la couleur de l'edt a blanc et les autres a gris
            emploidutempsLabel.setForeground(new java.awt.Color(255, 255, 255));
            recapitulatifLabel.setForeground(new java.awt.Color(153, 153, 153));
            gestionnaireLabel.setForeground(new java.awt.Color(153, 153, 153));
            reportingLabel.setForeground(new java.awt.Color(153, 153, 153));
            //l'edt est maintenant selectionne
            edtSelected = true;
            recapSelected = false;
            majSelected = false;
            reportingSelected = false;
        }
    }//GEN-LAST:event_emploidutempsLabelMouseClicked

    // Quand on clique sur le bouton recapitulatif de la periode
    private void recapitulatifLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recapitulatifLabelMouseClicked
        // TODO add your handling code here:
        if(!recapSelected) //Si il n'est pas selectionne
        {
            //On change la couleur de l'edt a blanc et les autres a gris
            emploidutempsLabel.setForeground(new java.awt.Color(153, 153, 153));
            recapitulatifLabel.setForeground(new java.awt.Color(255, 255, 255));
            gestionnaireLabel.setForeground(new java.awt.Color(153, 153, 153));
            reportingLabel.setForeground(new java.awt.Color(153, 153, 153));
            //l'edt est maintenant selectionne
            edtSelected = false;
            recapSelected = true;
            majSelected = false;
            reportingSelected = false;
        }
    }//GEN-LAST:event_recapitulatifLabelMouseClicked

    // Si on clique sur le bouton Gestionnaire de l'EDT
    private void gestionnaireLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionnaireLabelMouseClicked
        // TODO add your handling code here:
        if(!majSelected) //Si il n'est pas selectionne
        {
            //On change la couleur de l'edt a blanc et les autres a gris
            emploidutempsLabel.setForeground(new java.awt.Color(153, 153, 153));
            recapitulatifLabel.setForeground(new java.awt.Color(153, 153, 153));
            gestionnaireLabel.setForeground(new java.awt.Color(255, 255, 255));
            reportingLabel.setForeground(new java.awt.Color(153, 153, 153));
            //l'edt est maintenant selectionne
            edtSelected = false;
            recapSelected = false;
            majSelected = true;
            reportingSelected = false;
        }
    }//GEN-LAST:event_gestionnaireLabelMouseClicked

    // Si on appuie sur le bouton deconnexion
    private void deconnexionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexionLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_deconnexionLabelMouseClicked

    //Quand on clique sur le bouton Reporting
    private void reportingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportingLabelMouseClicked
        // TODO add your handling code here:
        
        if(!reportingSelected) //Si il n'est pas selectionne
        {
            //On change la couleur de l'edt a blanc et les autres a gris
            emploidutempsLabel.setForeground(new java.awt.Color(153, 153, 153));
            recapitulatifLabel.setForeground(new java.awt.Color(153, 153, 153));
            gestionnaireLabel.setForeground(new java.awt.Color(153, 153, 153));
            reportingLabel.setForeground(new java.awt.Color(255, 255, 255));
            //l'edt est maintenant selectionne
            edtSelected = false;
            recapSelected = false;
            majSelected = false;
            reportingSelected = true;
        }
    }//GEN-LAST:event_reportingLabelMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton27ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton29ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton30ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void jToggleButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton33ActionPerformed

    private void jToggleButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton34ActionPerformed

    private void jToggleButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton35ActionPerformed

    private void jToggleButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton36ActionPerformed

    private void jToggleButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton37ActionPerformed

    private void jToggleButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton38ActionPerformed

    private void jToggleButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton39ActionPerformed

    private void jToggleButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton40ActionPerformed

    private void jToggleButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton41ActionPerformed

    private void jToggleButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton42ActionPerformed

    private void jToggleButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton43ActionPerformed

    private void jToggleButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton44ActionPerformed

    private void jToggleButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton45ActionPerformed

    private void jToggleButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton46ActionPerformed

    private void jToggleButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton47ActionPerformed

    private void jToggleButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton48ActionPerformed

    private void jToggleButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton49ActionPerformed

    private void jToggleButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton50ActionPerformed

    private void jToggleButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton51ActionPerformed

    private void jToggleButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton52ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDT_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDT_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDT_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDT_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDT_Window().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel deconnexionLabel;
    private javax.swing.JLabel droitLabel;
    private javax.swing.JPanel edtAffichagePanel;
    private javax.swing.JPanel edtPanel;
    private javax.swing.JLabel emploidutempsLabel;
    private javax.swing.JPanel firstBackgroundPanel;
    private javax.swing.JLabel gestionnaireLabel;
    private javax.swing.JLabel heureLabel;
    private javax.swing.JLabel iconEce;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton49;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton51;
    private javax.swing.JToggleButton jToggleButton52;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JPanel leftGreenPanel;
    private javax.swing.JLabel nameUserLabel;
    private javax.swing.JLabel promotionLabel;
    private javax.swing.JLabel recapitulatifLabel;
    private javax.swing.JLabel reportingLabel;
    private javax.swing.JPanel semainePickerPanel;
    private javax.swing.JLabel tdLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
